apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - port: 80         # expondrá la api en el 8080
      targetPort: 8080 # escuchará en el 8080
  type: LoadBalancer
